domain: unixetc.github.io       # if you want to force HTTPS, specify the domain without the http at the start, e.g. example.com
url: https://unixetc.github.io  # the base hostname and protocol for your site, e.g. http://example.com
baseurl: /unixetc.github.io/      # place folder name if the site is served in a subfolder
